- hosts: all
  gather_facts: no
  vars:
    ntp_servers:
    - 1.2.3.4
    - 4.3.2.1
  tasks:
  - name: Parse NTP config
    ansible.utils.cli_parse:
      command: show running-config
      parser:
        name: ansible.utils.textfsm
        template_path: "templates/fsm/ntp.fsm"
      set_fact:
        current_ntp_servers
  - name: Debug
    ansible.builtin.debug:
      msg: "{{ current_ntp_servers | map(attribute='Host') }}"
  - name: Set NTP servers
    vars:
      to_add: "{{ ntp_servers | difference(current_ntp_servers | map(attribute='Host')) }}"
      to_delete: "{{ current_ntp_servers | map(attribute='Host') | difference(ntp_servers) }}"
    ios_config:
      src: "templates/config/ntp.j2"
