- hosts: all
  gather_facts: false
  tasks:
  - name: Configure NTP
    register: mod_out
    cisco.ios.ios_ntp_global:
      state: replaced
      config:
        authentication_keys:
        - algorithm: md5
          encryption: 7
          id: 2
          key: "0832595E0C0B161211190910"
        servers:
        - server: 1.2.3.4
          version: 2
          prefer: true
          key: 2
        - server: 4.3.2.1
          version: 2
          key: 2
  - ansible.builtin.debug:
      var: mod_out
