- hosts: all
  gather_facts: false
  tasks:
  - name: Configure NTP
    register: mod_output
    ansible.netcommon.network_resource:
      name: ntp_global
      state: overridden
      config: "{{ ntp_config }}"
  - ansible.builtin.debug:
      var: mod_output
