- hosts: clab-chinog-iol
  gather_facts: false
  tasks:
  - name: Delete all ACLs
    ansible.netcommon.network_resource:
      name: acls
      state: deleted
  - name: Configure 2 ACLs
    register: mod_output
    ansible.netcommon.network_resource:
      name: acls
      state: merged
      config:
      - afi: ipv4
        acls:
        - name: test_acl1
          acl_type: standard
          aces:
          - sequence: 10
            grant: permit
            source:
              address: 192.0.2.0
              wildcard_bits: 0.0.0.255
          - sequence: 20
            grant: deny
            source:
              any: true
        - name: test_acl2
          acl_type: extended
          aces:
          - sequence: 10
            grant: permit
            protocol: tcp
            source:
              any: true
            destination:
              address: 192.0.2.0
              wildcard_bits: 0.0.0.255
              port_protocol:
                eq: 22
          - sequence: 30
            grant: permit
            protocol: tcp
            source:
              any: true
            destination:
              address: 192.0.2.0
              wildcard_bits: 0.0.0.255
              port_protocol:
                eq: 443
  - ansible.builtin.debug:
      var: mod_output
  - name: Add ACE to test_acl2
    register: mod_output
    ansible.netcommon.network_resource:
      name: acls
      state: merged
      config:
      - afi: ipv4
        acls:
        - name: test_acl2
          acl_type: extended
          aces:
          - sequence: 20
            grant: deny
            protocol: tcp
            source:
              address: 100.64.0.0
              wildcard_bits: 0.63.255.255
            destination:
              address: 192.0.2.0
              wildcard_bits: 0.0.0.255
              port_protocol:
                eq: 443
  - ansible.builtin.debug:
      var: mod_output
  - name: Replace test_acl1
    register: mod_output
    ansible.netcommon.network_resource:
      name: acls
      state: replaced
      config:
      - afi: ipv4
        acls:
        - name: test_acl1
          acl_type: standard
          aces:
          - sequence: 10
            grant: permit
            source:
              host: 192.0.2.1
          - sequence: 20
            grant: deny
            source:
              any: true
  - ansible.builtin.debug:
      var: mod_output
  - name: Replace all ACLs with new ACL
    register: mod_output
    ansible.netcommon.network_resource:
      name: acls
      state: overridden
      config:
      - afi: ipv4
        acls:
        - name: test_acl3
          acl_type: extended
          aces:
          - sequence: 10
            protocol: ip
            grant: deny
            source:
              any: true
            destination:
              any: true
  - ansible.builtin.debug:
      var: mod_output
