network:
  vars:
    ansible_user: admin
    ansible_password: admin
    nm_configs: {}
    nm_states:
      system: overridden
      ntp_global: overridden
      snmp_server: overridden
      logging_global: overridden
      lldp_global: overridden
      interfaces: merged
      l3_interfaces: merged
      bgp_global: overridden
  hosts:
    clab-chinog-ceos:
      ansible_network_os: arista.eos.eos
      ansible_connection: ansible.netcommon.httpapi
      ansible_httpapi_use_ssl: yes
      ansible_httpapi_validate_certs: no
      nm_configs:
        ntp_global:
          local_interface: Ethernet1
          authentication_keys:
          - algorithm: md5
            encryption: 7
            id: 2
            key: "0832595E0C0B161211190910"
          servers:
          - server: 1.2.3.4
            key_id: 2
          - server: 4.3.2.1
            key_id: 2
        snmp_server:
          contact: support@example.com
          location: 123 Demo Way
          communities:
          - name: public
            ro: true
          - name: private
            rw: true
        logging_global:
          hosts:
          - name: 1.2.3.4
        interfaces:
        - name: Ethernet1
          description: clab-chinog-iol
          enabled: true
          mode: layer3
        l3_interfaces:
        - name: Loopback0
          ipv4:
          - address: 192.0.2.0/32
        - name: Ethernet1
          ipv4:
          - address: 10.0.0.0/31
        bgp_global:
          as_number: "65000"
          router_id: "192.0.2.0"
          redistribute:
          - protocol: connected
          neighbors:
          - neighbor_address: "10.0.0.1"
            remote_as: "65001"


    clab-chinog-iol:
      ansible_network_os: cisco.ios.ios
      ansible_connection: ansible.netcommon.network_cli
      nm_configs:
        ntp_global:
          source: Ethernet0/0
          authentication_keys:
          - algorithm: md5
            encryption: 7
            id: 2
            key: "0832595E0C0B161211190910"
          servers:
          - server: 1.2.3.4
            key_id: 2
          - server: 4.3.2.1
            key_id: 2
        snmp_server:
          contact: support@example.com
          location: 123 Demo Way
          communities:
          - name: public
            ro: true
          - name: private
            rw: true
        logging_global:
          hosts:
          - host: 1.2.3.4
        interfaces:
        - name: Ethernet0/1
          description: clab-chinog-ceos
          enabled: true
        l3_interfaces:
        - name: Loopback0
          ipv4:
          - address: 192.0.2.1/32
        - name: Ethernet0/1
          ipv4:
          - address: 10.0.0.1/31
        bgp_global:
          as_number: "65001"
          bgp:
            router_id:
              address: "192.0.2.1"
            default:
              ipv4_unicast: true
          redistribute:
          - connected:
              set: true
          neighbor:
          - neighbor_address: "10.0.0.0"
            remote_as: "65000"
        lldp_global:
          enabled: true
