- hosts: all
  gather_facts: false
  tasks:
  - name: Gather l3 info
    ansible.builtin.gather_facts:
      gather_subset:
      - "!all"
      gather_network_resources:
      - l3_interfaces
  - ansible.builtin.debug:
      var: ansible_facts
  - name: Gather l3 info
    when: not ansible_facts or "l3_interfaces" not in ansible_facts.network_resources
    ansible.builtin.gather_facts:
      gather_subset:
      - "!all"
      gather_network_resources:
      - l3_interfaces

